# Generated by Django 5.0 on 2024-10-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('education_level', models.CharField(choices=[('primary_first', 'ابتدایی دوره اول'), ('primary_second', 'ابتدایی دوره دوم'), ('middle_school', 'متوسطه دوره اول'), ('high_school', 'متوسطه دوره دوم')], max_length=100)),
                ('gender', models.CharField(choices=[('boy', 'پسرانه'), ('girl', 'دخترانه'), ('mixed', 'مختلط')], max_length=10)),
            ],
        ),
    ]
