# Generated by Django 5.0 on 2024-10-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examform',
            name='date_of_reference',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='examform',
            name='date_of_submission',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='examform',
            name='exam_book_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examform',
            name='receiver_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examform',
            name='reference_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examform',
            name='representative',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examform',
            name='submission_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='examform',
            name='submitter_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
