# Generated by Django 5.0 on 2024-10-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0002_examform_date_of_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examform',
            name='number_book',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='examform',
            name='number_paper_book',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='examform',
            name='school_name_2',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
