# Generated by Django 5.0 on 2024-10-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0003_examform_number_book_examform_number_paper_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examform',
            name='is_sealed',
            field=models.BooleanField(default=False, verbose_name='وضعیت پلمپ'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='date_of_reference',
            field=models.DateField(null=True, verbose_name='تاریخ ابلاغ'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='date_of_submission',
            field=models.DateField(null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='education_level',
            field=models.CharField(choices=[('primary_first', 'ابتدایی دوره اول'), ('primary_second', 'ابتدایی دوره دوم'), ('middle_school', 'متوسطه دوره اول'), ('high_school', 'متوسطه دوره دوم')], max_length=100, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='exam_book_year',
            field=models.CharField(max_length=100, null=True, verbose_name='سال تحصیلی'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='gender',
            field=models.CharField(choices=[('boy', 'پسرانه'), ('girl', 'دخترانه'), ('mixed', 'مختلط')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='number_book',
            field=models.IntegerField(null=True, verbose_name='تعداد دفتر امتحانات'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='number_paper_book',
            field=models.IntegerField(null=True, verbose_name='تعداد صفحات دفتر'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='receiver_name',
            field=models.CharField(max_length=255, null=True, verbose_name='نام و نام خانوادگی تحویل\u200cگیرنده'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='reference_number',
            field=models.CharField(max_length=100, null=True, verbose_name='شماره استناد ابلاغ'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='representative',
            field=models.CharField(max_length=255, null=True, verbose_name='نماینده اداره'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='school_name',
            field=models.CharField(max_length=255, verbose_name='نام آموزشگاه'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='school_name_2',
            field=models.CharField(max_length=256, null=True, verbose_name='نام آموزشگاه (دومین نام)'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='submission_date',
            field=models.DateField(null=True, verbose_name='تاریخ تحویل نهایی'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='submitter_name',
            field=models.CharField(max_length=255, null=True, verbose_name='نام و نام خانوادگی تحویل\u200cدهنده'),
        ),
    ]
