# Generated by Django 5.0 on 2024-10-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0005_alter_examform_date_of_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examform',
            name='date_of_reference',
            field=models.DateField(null=True, verbose_name='تاریخ ابلاغ'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='date_of_submission',
            field=models.DateField(null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='submission_date',
            field=models.DateField(null=True, verbose_name='تاریخ تحویل نهایی'),
        ),
    ]
