# Generated by Django 5.0 on 2024-10-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0007_alter_examform_date_of_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examform',
            name='exam_book_year',
            field=models.CharField(blank=True, choices=[('1398-1399', '1398-1399'), ('1399-1400', '1399-1400'), ('1400-1401', '1400-1401'), ('1401-1402', '1401-1402'), ('1402-1403', '1402-1403'), ('1403-1404', '1403-1404'), ('1404-1405', '1404-1405'), ('1405-1406', '1405-1406'), ('1406-1407', '1406-1407'), ('1407-1408', '1407-1408'), ('1408-1409', '1408-1409'), ('1409-1410', '1409-1410')], max_length=100, null=True, verbose_name='سال تحصیلی'),
        ),
    ]
